const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..', '..', 'miniprogram')
const settingsTemplate = fs.readFileSync(path.join(root, 'pages', 'settings', 'index.wxml'), 'utf8')
const settingsScript = fs.readFileSync(path.join(root, 'pages', 'settings', 'index.js'), 'utf8')
const recommendTemplate = fs.readFileSync(path.join(root, 'pages', 'recommend', 'index.wxml'), 'utf8')
const recommendScript = fs.readFileSync(path.join(root, 'pages', 'recommend', 'index.js'), 'utf8')

test('restriction management is a registered page with an enabled Settings entry', () => {
  const appConfig = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'))
  assert.ok(appConfig.pages.includes('pages/restrictions/index'))
  assert.match(settingsTemplate, /成员忌口/)
  assert.match(settingsTemplate, /bindtap="goRestrictions"/)
  assert.doesNotMatch(settingsTemplate, /家庭忌口<\/view><\/view><text[^>]*>即将开放/s)
  assert.match(settingsScript, /goRestrictions\(\)/)
})

test('restriction page exposes member restriction management, real APIs, empty/error states and guarded mutations', () => {
  const pageRoot = path.join(root, 'pages', 'restrictions')
  const script = fs.readFileSync(path.join(pageRoot, 'index.js'), 'utf8')
  const template = fs.readFileSync(path.join(pageRoot, 'index.wxml'), 'utf8')
  const styles = fs.readFileSync(path.join(pageRoot, 'index.wxss'), 'utf8')
  const pageConfig = JSON.parse(fs.readFileSync(path.join(pageRoot, 'index.json'), 'utf8'))
  assert.match(script, /\/families\/current/)
  assert.match(script, /family-members\/\$\{.*\}\/restrictions/)
  assert.match(script, /, 'POST',/)
  assert.match(script, /, 'DELETE'/)
  assert.match(script, /savingIngredientId/)
  assert.match(script, /deletingIngredientId/)
  assert.match(template, /activeMembers/)
  assert.match(template, /暂无家庭成员忌口/)
  assert.match(template, /添加忌口/)
  assert.match(template, /bindtap="removeRestriction"/)
  assert.match(template, /restrictions-nav__slot/)
  assert.match(template, /restrictions-nav__title/)
  assert.match(template, /assets\/icons\/recipes\/back\.png/)
  assert.match(styles, /width: 186rpx/)
  assert.match(styles, /position: fixed/)
  assert.match(styles, /margin: 0 0 0 auto/)
  assert.match(styles, /width: auto !important/)
  assert.match(styles, /padding: 13rpx 16rpx/)
  assert.match(styles, /border-radius: 50% !important/)
  assert.equal(pageConfig.navigationStyle, 'custom')
})

test('restriction page loads and renders every member restriction as grouped sections', () => {
  const pageRoot = path.join(root, 'pages', 'restrictions')
  const script = fs.readFileSync(path.join(pageRoot, 'index.js'), 'utf8')
  const template = fs.readFileSync(path.join(pageRoot, 'index.wxml'), 'utf8')

  assert.match(script, /Promise\.all/)
  assert.match(script, /restrictionSections/)
  assert.match(script, /const activeMembers = members\.map/)
  assert.doesNotMatch(script, /scopedMembers/)
  assert.doesNotMatch(script, /members\.filter\(\(member\) => Number\(member\.id\) === currentMemberId\)/)
  assert.match(template, /wx:for="{{restrictionSections}}"/)
  assert.match(template, /item\.restrictions/)
  assert.match(template, /data-member-id="{{item\.memberId}}"/)
  assert.match(template, /bindtap="openAdd"/)
})

test('restriction page clears stale member data before and after a failed reload', () => {
  const script = fs.readFileSync(path.join(root, 'pages', 'restrictions', 'index.js'), 'utf8')
  assert.match(script, /this\.setData\(\{[\s\S]*activeMembers:\s*\[\][\s\S]*restrictionSections:\s*\[\][\s\S]*restrictionTotal:\s*0/)
  assert.match(script, /catch \(error\) \{[\s\S]*this\.setData\(\{[\s\S]*activeMembers:\s*\[\][\s\S]*restrictionSections:\s*\[\][\s\S]*restrictionTotal:\s*0/)
})

test('restriction groups use the compact numbered-list presentation', () => {
  const pageRoot = path.join(root, 'pages', 'restrictions')
  const template = fs.readFileSync(path.join(pageRoot, 'index.wxml'), 'utf8')
  const styles = fs.readFileSync(path.join(pageRoot, 'index.wxss'), 'utf8')

  assert.match(template, /wx:for-index="restrictionIndex"/)
  assert.match(template, /restrictions-row__index/)
  assert.match(template, />\+<\/button>/)
  assert.doesNotMatch(template, />[^<]*添加忌口<\/button>/)
  assert.doesNotMatch(template, /restrictions-card__helper/)
  assert.doesNotMatch(template, /restriction-member-group__role/)
  assert.doesNotMatch(template, /按成员分类展示/)
  assert.match(styles, /\.restriction-member-group__add[\s\S]*width: 64rpx/)
  assert.match(styles, /\.restrictions-remove[\s\S]*background: transparent/)
  assert.match(styles, /\.restrictions-remove[\s\S]*border-radius: 0/)
})

test('recommendation only presents the persisted family restriction source', () => {
  assert.match(recommendTemplate, /\{\{mealTypeLabel\}\}想吃什么/)
  assert.doesNotMatch(recommendTemplate, /toggleRestriction|家庭忌口|draftRestrictionOptions/)
  assert.doesNotMatch(recommendScript, /draftRestrictionOptions|toggleRestriction\(|familyRestrictions/)
})
