USE mealpilot;

-- Insert-only backfill copied from the controlled recipe metadata in 02_seed.sql.
-- The current business database was verified against the seed: recipe IDs 1-48
-- have the same titles and categories. INSERT IGNORE makes this safe to rerun;
-- it never removes or rewrites existing metadata.
INSERT IGNORE INTO recipe_tags (recipe_id, tag_type, tag_value) VALUES
(1,'taste','sweet'),(1,'taste','sour'),(1,'method','stir_fry'),
(2,'taste','light'),(2,'taste','savory'),(2,'dietary','vegetarian'),(2,'method','stir_fry'),
(3,'taste','light'),(3,'taste','savory'),(3,'dietary','seafood'),(3,'method','soup'),
(4,'taste','savory'),(4,'method','stir_fry'),
(5,'taste','light'),(5,'taste','savory'),(5,'dietary','vegetarian'),(5,'method','stir_fry'),
(6,'taste','light'),(6,'taste','savory'),(6,'method','soup'),
(7,'taste','savory'),(7,'method','stew'),
(8,'taste','light'),(8,'taste','savory'),(8,'dietary','seafood'),(8,'method','steam'),
(9,'taste','savory'),(9,'method','stir_fry'),
(10,'taste','savory'),(10,'method','stew'),
(11,'taste','savory'),(11,'method','stew'),
(12,'taste','light'),(12,'taste','savory'),(12,'dietary','seafood'),(12,'method','stir_fry'),
(13,'taste','sweet'),(13,'taste','sour'),(13,'method','stir_fry'),
(14,'taste','savory'),(14,'method','stew'),
(15,'taste','savory'),(15,'method','stir_fry'),
(16,'taste','savory'),(16,'method','stir_fry'),
(17,'taste','savory'),(17,'method','stir_fry'),
(18,'taste','savory'),(18,'dietary','seafood'),(18,'method','stew'),
(19,'taste','spicy'),(19,'taste','sweet'),(19,'taste','savory'),(19,'method','stir_fry'),
(20,'taste','light'),(20,'taste','sweet'),(20,'dietary','vegetarian'),(20,'method','stir_fry'),
(21,'taste','savory'),(21,'dietary','vegetarian'),(21,'method','stir_fry'),
(22,'taste','light'),(22,'taste','savory'),(22,'dietary','vegetarian'),(22,'method','stir_fry'),
(23,'taste','light'),(23,'taste','sweet'),(23,'dietary','vegetarian'),(23,'method','stir_fry'),
(24,'taste','savory'),(24,'dietary','vegetarian'),(24,'method','stew'),
(25,'taste','savory'),(25,'dietary','vegetarian'),(25,'method','stir_fry'),
(26,'taste','sour'),(26,'dietary','vegetarian'),(26,'method','stir_fry'),
(27,'taste','light'),(27,'taste','sweet'),(27,'dietary','vegetarian'),(27,'method','stir_fry'),
(28,'taste','light'),(28,'taste','sour'),(28,'dietary','vegetarian'),
(29,'taste','light'),(29,'taste','savory'),(29,'dietary','vegetarian'),(29,'method','stir_fry'),
(30,'taste','light'),(30,'taste','savory'),(30,'dietary','vegetarian'),(30,'method','stew'),
(31,'taste','light'),(31,'taste','savory'),(31,'method','soup'),
(32,'taste','sour'),(32,'taste','savory'),(32,'method','stew'),
(33,'taste','sweet'),(33,'taste','savory'),(33,'method','soup'),
(34,'taste','light'),(34,'taste','savory'),(34,'dietary','vegetarian'),(34,'method','soup'),
(35,'taste','savory'),(35,'dietary','seafood'),(35,'method','soup'),
(36,'taste','light'),(36,'taste','sweet'),(36,'dietary','seafood'),(36,'method','soup'),
(37,'taste','savory'),(37,'method','stew'),
(38,'taste','savory'),(38,'method','soup'),
(39,'taste','savory'),(39,'method','stew'),
(40,'taste','sweet'),(40,'dietary','vegetarian'),(40,'method','stew'),
(41,'taste','savory'),(41,'method','stew'),
(42,'taste','savory'),(42,'dietary','seafood'),
(43,'taste','savory'),(43,'method','steam'),
(44,'taste','savory'),
(45,'taste','savory'),(45,'method','stir_fry'),
(46,'taste','savory'),(46,'dietary','seafood'),(46,'method','stir_fry'),
(47,'taste','sweet'),(47,'dietary','vegetarian'),(47,'method','steam'),
(48,'taste','sweet'),(48,'dietary','vegetarian'),(48,'method','stew');
