const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const schema = fs.readFileSync(path.join(root, 'database/01_schema.sql'), 'utf8')
const migrationPath = path.join(root, 'database/04_recommendation_refactor_r1.sql')
const amendmentPath = path.join(root, 'database/05_recommendation_run_nullable_legacy.sql')
const backfillPath = path.join(root, 'database/06_recipe_tag_metadata_backfill.sql')
const removalPath = path.join(root, 'database/07_remove_cuisine_tags.sql')

test('T1 schema defines the tag definition catalog and association relation', () => {
  assert.match(schema, /CREATE TABLE tag_definitions \(/)
  assert.match(schema, /kind ENUM\('system', 'custom'\) NOT NULL/)
  assert.match(schema, /UNIQUE KEY uq_tag_system_code \(kind, code\)/)
  assert.match(schema, /UNIQUE KEY uq_tag_family_name \(family_id, normalized_name\)/)
  assert.match(schema, /CREATE TABLE recipe_tags \(/)
  assert.match(schema, /tag_id BIGINT UNSIGNED NOT NULL/)
  assert.match(schema, /PRIMARY KEY \(recipe_id, tag_id\)/)
  assert.match(schema, /FOREIGN KEY \(recipe_id\) REFERENCES recipes\(id\) ON DELETE CASCADE/)
  assert.match(schema, /FOREIGN KEY \(tag_id\) REFERENCES tag_definitions\(id\) ON DELETE RESTRICT/)
  assert.match(schema, /CREATE TABLE recipe_tags_legacy \(/)
})

test('R1.1 schema makes legacy-only Run fields nullable and keeps canonical snapshots nullable', () => {
  assert.match(schema, /max_cook_minutes SMALLINT UNSIGNED NULL/)
  assert.match(schema, /mode ENUM\('balanced', 'healthy', 'quick'\) NULL/)
  assert.match(schema, /total_score DECIMAL\(6,2\) NULL/)
  assert.match(schema, /total_cook_minutes SMALLINT UNSIGNED NULL/)
  assert.match(schema, /score_breakdown JSON NULL/)
  assert.match(schema, /max_prep_minutes SMALLINT UNSIGNED NULL/)
  assert.match(schema, /CONSTRAINT ck_recommendation_prep_limit CHECK \(max_prep_minutes IS NULL OR max_prep_minutes BETWEEN 10 AND 480\)/)
  assert.match(schema, /menu_structure JSON NULL/)
  assert.match(schema, /session_preferences JSON NULL/)
})

test('R1 candidate schema defines rank, uniqueness and cascade boundaries', () => {
  assert.match(schema, /CREATE TABLE recommendation_candidates \(/)
  assert.match(schema, /UNIQUE KEY uq_recommendation_candidate_rank \(recommendation_run_id, candidate_rank\)/)
  assert.match(schema, /CHECK \(candidate_rank BETWEEN 1 AND 3\)/)
  assert.match(schema, /FOREIGN KEY \(recommendation_run_id\) REFERENCES recommendation_runs\(id\) ON DELETE CASCADE/)

  assert.match(schema, /CREATE TABLE recommendation_candidate_items \(/)
  assert.match(schema, /PRIMARY KEY \(recommendation_candidate_id, recipe_id\)/)
  assert.match(schema, /UNIQUE KEY uq_candidate_item_slot \(recommendation_candidate_id, slot_no\)/)
  assert.match(schema, /CHECK \(slot_no >= 1\)/)
  assert.match(schema, /FOREIGN KEY \(recommendation_candidate_id\) REFERENCES recommendation_candidates\(id\) ON DELETE CASCADE/)
  assert.match(schema, /FOREIGN KEY \(recipe_id\) REFERENCES recipes\(id\) ON DELETE RESTRICT/)
})

test('R1 upgrade script is additive and covers every new structure', () => {
  assert.equal(fs.existsSync(migrationPath), true, 'R1 additive upgrade script must exist')
  const migration = fs.readFileSync(migrationPath, 'utf8')
  assert.match(migration, /ALTER TABLE recommendation_runs/i)
  assert.doesNotMatch(migration, /ADD COLUMN IF NOT EXISTS/i, 'MySQL 8.0.45 does not support ADD COLUMN IF NOT EXISTS')
  assert.match(migration, /information_schema\.columns/i)
  assert.match(migration, /max_prep_minutes/i)
  assert.match(migration, /ck_recommendation_prep_limit/i)
  assert.match(migration, /menu_structure/i)
  assert.match(migration, /session_preferences/i)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS recipe_tags/i)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS recommendation_candidates/i)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS recommendation_candidate_items/i)
  assert.doesNotMatch(migration, /DROP TABLE|TRUNCATE|DELETE FROM|DROP DATABASE/i)
})

test('R1.1 amendment migration changes only legacy Run nullability', () => {
  assert.equal(fs.existsSync(amendmentPath), true, 'R1.1 amendment migration must exist')
  const migration = fs.readFileSync(amendmentPath, 'utf8')
  assert.match(migration, /ALTER TABLE recommendation_runs/i)
  assert.match(migration, /MODIFY COLUMN max_cook_minutes SMALLINT UNSIGNED NULL/i)
  assert.match(migration, /MODIFY COLUMN mode ENUM\('balanced', 'healthy', 'quick'\) NULL/i)
  assert.match(migration, /MODIFY COLUMN total_score DECIMAL\(6,2\) NULL/i)
  assert.match(migration, /MODIFY COLUMN total_cook_minutes SMALLINT UNSIGNED NULL/i)
  assert.match(migration, /MODIFY COLUMN score_breakdown JSON NULL/i)
  assert.doesNotMatch(migration, /DROP COLUMN|DELETE FROM|TRUNCATE|DROP TABLE|DROP DATABASE/i)
})

test('R1.1 migration preserves Candidate tables and does not rewrite historical Runs', () => {
  const migration = fs.readFileSync(amendmentPath, 'utf8')
  assert.doesNotMatch(migration, /recommendation_candidates\s+WHERE|recommendation_candidate_items\s+WHERE|recommendation_runs\s+WHERE/i)
  assert.doesNotMatch(migration, /CREATE TABLE|DROP TABLE|ALTER TABLE recommendation_candidates|ALTER TABLE recommendation_candidate_items/i)
})

test('T1 seed includes the ten approved tag definitions without legacy derived metadata', () => {
  const seed = fs.readFileSync(path.join(root, 'database/02_seed.sql'), 'utf8')
  assert.match(seed, /INSERT(?:\s+IGNORE)?\s+INTO recipe_tags/i)
  assert.match(seed, /INSERT INTO tag_definitions/i)
  for (const code of ['spicy', 'sour', 'sweet', 'seafood', 'fish', 'shrimp', 'crab', 'bake', 'steam', 'fried']) assert.match(seed, new RegExp(`'${code}'`))
  assert.doesNotMatch(seed, /'cuisine'/i)
  assert.doesNotMatch(seed, /'vegetarian'/i)
  assert.doesNotMatch(seed, /'stir_fry'/i)
  assert.doesNotMatch(seed, /'stew'/i)
  assert.doesNotMatch(seed, /'soup'/i)
  assert.doesNotMatch(seed, /'high_protein'/i)
  assert.doesNotMatch(seed, /'seasonal'/i)
  assert.match(seed, /INSERT INTO ingredient_seasons/i)
})

test('R1 metadata contract exposes only the approved controlled values', () => {
  const metadata = require('../src/services/recommendation-metadata')
  assert.deepEqual(metadata.RECIPE_TAG_TYPES, ['taste', 'dietary', 'method'])
  assert.equal(metadata.isAllowedRecipeTag('cuisine', 'home'), false)
  assert.equal(metadata.isAllowedRecipeTag('taste', 'spicy'), true)
  assert.equal(metadata.isAllowedRecipeTag('dietary', 'high_protein'), false)
  assert.equal(metadata.isAllowedRecipeTag('method', 'steam'), true)
  assert.equal(metadata.isAllowedRecipeTag('unknown', 'spicy'), false)
})

test('R1 metadata backfill is insert-only, idempotent, and covers seed tag types', () => {
  assert.equal(fs.existsSync(backfillPath), true, 'metadata backfill must exist')
  const backfill = fs.readFileSync(backfillPath, 'utf8')
  assert.match(backfill, /INSERT\s+IGNORE\s+INTO\s+recipe_tags/i)
  assert.match(backfill, /'taste'/i)
  assert.doesNotMatch(backfill, /'cuisine'/i)
  assert.match(backfill, /'dietary'/i)
  assert.match(backfill, /'method'/i)
  assert.doesNotMatch(backfill, /UPDATE\s+recipe_tags|DELETE\s+FROM\s+recipe_tags|TRUNCATE|DROP\s+TABLE/i)
})

test('cuisine tag removal migration deletes obsolete rows and removes the enum option', () => {
  assert.equal(fs.existsSync(removalPath), true, 'cuisine removal migration must exist')
  const migration = fs.readFileSync(removalPath, 'utf8')
  assert.match(migration, /DELETE\s+FROM\s+recipe_tags\s+WHERE\s+tag_type\s*=\s*'cuisine'/i)
  assert.match(migration, /MODIFY\s+COLUMN\s+tag_type\s+ENUM\('taste',\s*'dietary',\s*'method'\)\s+NOT NULL/i)
})
