const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const pageRoot = path.join(root, 'pages', 'family-management')

test('family management is a registered real page with family and member actions', () => {
  const appConfig = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'))
  const template = fs.readFileSync(path.join(pageRoot, 'index.wxml'), 'utf8')
  const script = fs.readFileSync(path.join(pageRoot, 'index.js'), 'utf8')
  const styles = fs.readFileSync(path.join(pageRoot, 'index.wxss'), 'utf8')
  const config = JSON.parse(fs.readFileSync(path.join(pageRoot, 'index.json'), 'utf8'))

  assert.ok(appConfig.pages.includes('pages/family-management/index'))
  assert.equal(config.navigationStyle, 'custom')
  assert.match(template, /家庭信息/)
  assert.match(template, /家庭成员/)
  assert.match(template, /bindtap="renameFamily"/)
  assert.match(template, /assets\/icons\/recipes\/edit\.png/)
  assert.match(styles, /\.family-hero__edit\s*\{[^}]*flex:\s*0 0 64rpx;[^}]*max-width:\s*64rpx/s)
  assert.match(styles, /\.family-member__manage\s*\{[^}]*width:\s*82rpx;[^}]*flex:\s*0 0 82rpx;[^}]*max-width:\s*82rpx/s)
  assert.match(template, /bindtap="leaveFamily"/)
  assert.match(template, /bindtap="createFamily"/)
  assert.match(template, /bindtap="joinFamily"/)
  assert.match(template, /bindtap="copyInviteCode"/)
  assert.match(template, /bindtap="refreshInviteCode"/)
  assert.match(template, /刷新邀请码/)
  assert.doesNotMatch(template, /请联系管理员获取邀请码/)
  assert.match(template, /bindtap="manageMember"/)
  assert.match(script, /request\('\/families\/current'\)/)
  assert.match(script, /families\/current\/name/)
  assert.match(script, /renameFamily\(/)
  assert.match(script, /request\('\/families\/leave', 'POST'/)
  assert.match(script, /\/families\/current\/members\/\$\{memberId\}\/role/)
  assert.match(script, /\/families\/current\/members\/\$\{memberId\}/)
  assert.match(script, /families\/current\/transfer-ownership/)
  assert.match(script, /request\('\/families\/current\/invite-code\/refresh', 'POST'/)
  assert.match(script, /refreshInviteCode\(/)
  assert.match(script, /loading: true, error: '', membership: null, family: null, members: \[\]/)
  assert.match(script, /管理员/)
  assert.match(script, /成员/)
  assert.match(styles, /\.family-invite__refresh\s*\{[^}]*border:[^}]*background:\s*transparent/s)
})

test('settings opens the family page and displays the family permission', () => {
  const settingsScript = fs.readFileSync(path.join(root, 'pages', 'settings', 'index.js'), 'utf8')
  const settingsTemplate = fs.readFileSync(path.join(root, 'pages', 'settings', 'index.wxml'), 'utf8')

  assert.match(settingsScript, /wx\.navigateTo\(\{ url: '\/pages\/family-management\/index' \}\)/)
  assert.match(settingsScript, /userRoleLabel/)
  assert.match(settingsScript, /canManageFamily/)
  assert.match(settingsTemplate, /\{\{userRoleLabel\}\}/)
  assert.doesNotMatch(settingsTemplate, /allowDevLogin \? '本地开发身份' : '微信登录用户'/)
  assert.doesNotMatch(settingsTemplate, /联系管理员获取邀请码/)
  assert.match(settingsTemplate, /class="settings-quick-card" bindtap="copyCode"/)
})
