const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (...segments) => fs.readFileSync(path.join(root, ...segments), 'utf8')
const tags = require('../utils/tags')

test('T4 tag helpers keep API order and preserve selected recipe tags', () => {
  const catalog = tags.flattenTagCatalog({
    systemTags: [{ id: 1, name: '辣', kind: 'system' }],
    customTags: [{ id: 20, name: '家常', kind: 'custom' }]
  })
  assert.deepEqual(catalog.map((tag) => tag.id), [1, 20])
  assert.deepEqual(tags.normalizeTagIds([20, '1', 20, 0, 'bad']), [20, 1])
  assert.deepEqual(tags.toggleTagId([1], 20), [1, 20])
  assert.deepEqual(tags.toggleTagId([1, 20], 20), [1])
  const options = tags.decorateTagOptions(catalog, [1], [])
  assert.deepEqual(options.map(({ id, selected }) => ({ id, selected })), [
    { id: 1, selected: true },
    { id: 20, selected: false }
  ])
})

test('T4 recipe list uses list response tags inline and limits badges to three', () => {
  const script = read('pages', 'recipes', 'index.js')
  const template = read('pages', 'recipes', 'index.wxml')
  const styles = read('pages', 'recipes', 'index.wxss')
  assert.match(script, /displayTags\(recipe\.tags, 3\)/)
  assert.doesNotMatch(script, /recipes\/\$\{.*\}.*tags|Promise\.all\(.*recipes/s)
  assert.match(template, /recipe-card__title-row/)
  assert.match(template, /wx:for="\{\{item\.displayTags\}\}"/)
  assert.match(styles, /linear-gradient\(135deg,\s*#FBE7A2,\s*#F3C75F\)/i)
  assert.match(styles, /\.recipe-card__badge\s*\{[^}]*border-radius:\s*8rpx;[^}]*padding:\s*3rpx 10rpx;/s)
  assert.deepEqual(tags.displayTags([{ id: 1, name: '一' }, { id: 2, name: '二' }, { id: 3, name: '三' }, { id: 4, name: '四' }], 3).map((tag) => tag.id), [1, 2, 3])
  assert.deepEqual(tags.displayTags([], 3), [])
  assert.doesNotMatch(template, /无标签|更多标签|\+\d/)
  assert.match(styles, /\.recipe-card__title\s*\{[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap;/s)
})

test('T4 recipe detail renders every linked tag once beside the title', () => {
  const template = read('pages', 'recipe-detail', 'index.wxml')
  const styles = read('pages', 'recipe-detail', 'index.wxss')
  assert.match(template, /detail-title-row/)
  assert.match(template, /wx:for="\{\{recipe\.tags\}\}"/)
  assert.equal((template.match(/wx:for="\{\{recipe\.tags\}\}"/g) || []).length, 1)
  assert.doesNotMatch(styles, /detail-tag--inactive/)
})

test('T4 recipe form loads tags, persists tagIds, creates custom tags, and opens shared management page', () => {
  const script = read('pages', 'recipe-form', 'index.js')
  const template = read('pages', 'recipe-form', 'index.wxml')
  assert.match(script, /request\('\/tags'\)/)
  assert.match(script, /request\('\/tags', 'POST', \{ name \}\)/)
  assert.match(script, /tagIds:\s*this\.data\.selectedTagIds/)
  assert.match(script, /decorateTagOptions/)
  assert.match(script, /selectedTagIds/)
  assert.match(script, /selectedTagIds:\s*\[\]/)
  assert.match(script, /Number\(error\.status\) === 409 \? '这个标签已经存在'/)
  assert.match(script, /creatingTag/)
  assert.match(template, /标签/)
  assert.match(template, /bindtap="toggleRecipeTag"/)
  assert.match(template, /bindtap="createCustomTag"/)
  assert.match(script, /openTagManagement\(\)/)
  assert.match(script, /wx\.navigateTo\(\{ url: '\/pages\/tag-management\/index' \}\)/)
  assert.match(script, /_tagManagementOpened = true/)
  assert.match(script, /validTagIds = new Set/)
  assert.match(template, /bindtap="openTagManagement"/)
  assert.doesNotMatch(template, /deleteCustomTag|tagManageMode/)
  assert.match(template, /bindtap="retryTags"/)
  assert.match(template, /tagLoading/)
  assert.match(template, /tagError/)
})

test('T4 recipe form limits tags to three representative choices', () => {
  const script = read('pages', 'recipe-form', 'index.js')
  const template = read('pages', 'recipe-form', 'index.wxml')
  assert.match(script, /selectedTagIds\.length\s*>=\s*3/)
  assert.match(script, /createCustomTag\(\)[\s\S]*selectedTagIds\.length\s*>=\s*3/)
  assert.match(script, /最多选择3个最有代表性的标签/)
  assert.match(template, /\{\{selectedTagIds\.length\}\}\/3/)
  assert.match(template, /最多选择 3 个/)
})

test('T4 tag management is a shared registered page for Settings and Recipe Form', () => {
  const appConfig = JSON.parse(read('app.json'))
  const script = read('pages', 'recipe-form', 'index.js')
  const template = read('pages', 'recipe-form', 'index.wxml')
  const settingsTemplate = read('pages', 'settings', 'index.wxml')
  const settingsScript = read('pages', 'settings', 'index.js')
  const pageTemplate = read('pages', 'tag-management', 'index.wxml')
  const pageScript = read('pages', 'tag-management', 'index.js')
  const pageStyles = read('pages', 'tag-management', 'index.wxss')
  assert.ok(appConfig.pages.includes('pages/tag-management/index'))
  assert.equal(appConfig.pages.includes('pages/preferences/index'), false)
  assert.match(settingsTemplate, /标签管理/)
  assert.match(settingsTemplate, /bindtap="goTagManagement"/)
  assert.match(settingsScript, /wx\.navigateTo\(\{ url: '\/pages\/tag-management\/index' \}\)/)
  assert.match(script, /openTagManagement\(\)/)
  assert.match(template, /bindtap="openTagManagement"/)
  assert.match(pageTemplate, /自定义标签/)
  assert.match(pageTemplate, /系统标签不可修改或删除/)
  assert.match(pageTemplate, /bindtap="renameTag"/)
  assert.match(pageTemplate, /bindtap="deleteTag"/)
  assert.match(pageScript, /request\('\/tags'\)/)
  assert.match(pageScript, /request\(`\/tags\/\$\{tagId\}`, 'DELETE'\)/)
  assert.match(pageStyles, /tag-management-card--custom/)
  assert.match(pageStyles, /tag-management-system-chip/)
  assert.match(template, /tag-section-actions/)
  assert.match(template, /tag-section-action--manage/)
  assert.match(template, /tag-section-action--create/)
})

test('T4 recommendation accepts zero or many API tag ids without frontend semantic inference', () => {
  const script = read('pages', 'recommend', 'index.js')
  const template = read('pages', 'recommend', 'index.wxml')
  const preferenceState = require('../pages/recommend/preference-state')
  assert.deepEqual(preferenceState.buildCanonicalRequest({
    menuDate: '2026-09-09', peopleCount: 2, maxPrepMinutes: 60,
    structure: { meat: 1, vegetable: 1, soup: 0, staple: 0 }, preferences: {}
  }).preferences, { selectedTagIds: [] })
  assert.deepEqual(preferenceState.toggleTagId([1, 2], 3), [1, 2, 3])
  assert.match(script, /flattenTagCatalog\(await request\('\/tags'\)\)/)
  assert.match(script, /tagCatalog:\s*\[\]/)
  assert.match(script, /tagOptions:\s*\[\]/)
  assert.match(script, /tagError/)
  assert.doesNotMatch(template, /想吃辣|偏甜|清淡|素食倾向|高蛋白|优先当季食材/)
  assert.doesNotMatch(script, /fish.*seafood|shrimp.*seafood|steam.*light/i)
})

test('recommendation and menu dish cards render persisted recipe tags', () => {
  const recommendationScript = read('pages', 'recommend', 'index.js')
  const recommendationTemplate = read('pages', 'recommend', 'index.wxml')
  const recommendationStyles = read('pages', 'recommend', 'index.wxss')
  const menuScript = read('pages', 'menu', 'index.js')
  const menuTemplate = read('pages', 'menu', 'index.wxml')
  const menuStyles = read('pages', 'menu', 'index.wxss')
  assert.match(recommendationScript, /displayTags\(item\.tags, 3\)/)
  assert.match(recommendationTemplate, /item\.displayTags/)
  assert.match(recommendationStyles, /\.recommend-dish__tag\s*\{/) 
  assert.match(menuScript, /displayTags\(recipe\.tags, 3\)/)
  assert.match(menuTemplate, /item\.displayTags/)
  assert.match(menuStyles, /\.menu-dish__tag\s*\{/) 
})
